module.exports = {
    beforeEach: browser => {
        browser.url('https://devmountain-qa.github.io/employee-manager/1.2_Version/index.html')
    },
    after: browser => {
        browser.end()
    },
    'check that you can save invalid fields': browser => {
        var employeeInfo = { phone: '0000000000000000000000000' }
        browser
            // .waitForElementVisible('.titlebar')
            .click('[name="employee1"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', employeeInfo.phone)
            .click('[name="save"]')
            .verify.valueContains('input[name="phoneEntry"]', '0000000000000000000000000')
            .click('[name="employee2"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', employeeInfo.phone)
            .click('[name="save"]')
            .verify.valueContains('input[name="phoneEntry"]', '0000000000000000000000000')
            .click('[name="employee3"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', employeeInfo.phone)
            .click('[name="save"]')
            .verify.valueContains('input[name="phoneEntry"]', '0000000000000000000000000')
            .click('[name="employee4"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', employeeInfo.phone)
            .click('[name="save"]')
            .verify.valueContains('input[name="phoneEntry"]', '0000000000000000000000000')
            .click('[name="employee5"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', employeeInfo.phone)
            .click('[name="save"]')
            .verify.valueContains('input[name="phoneEntry"]', '0000000000000000000000000')
            .click('[name="employee6"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', employeeInfo.phone)
            .click('[name="save"]')
            .verify.valueContains('input[name="phoneEntry"]', '0000000000000000000000000')
            .click('[name="employee7"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', employeeInfo.phone)
            .click('[name="save"]')
            .verify.valueContains('input[name="phoneEntry"]', '0000000000000000000000000')
            .click('[name="employee8"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', employeeInfo.phone)
            .click('[name="save"]')
            .verify.valueContains('input[name="phoneEntry"]', '0000000000000000000000000')
            .click('[name="employee9"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', employeeInfo.phone)
            .click('[name="save"]')
            .verify.valueContains('input[name="phoneEntry"]', '0000000000000000000000000')
            .click('[name="employee10"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', employeeInfo.phone)
            .click('[name="save"]')
            .verify.valueContains('input[name="phoneEntry"]', '0000000000000000000000000')
    }
}
//pass is a fail
