module.exports = [
    {
        drop1: '@home',
        drop1res: 'Home Purchase',
        drop2: '[value="Single Family Home"]',
        drop2res: 'Single Family Home',
        city: 'lehi',
        prop: '[value="Primary Home"]',
        propres: 'Primary Home',
        idk: '[name="yesButton"]',
        idkres: 'True',
        idk2: '[name="noButton"]',
        idk2res:'False',
        pp: '100000',
        dp: '10000',
        credit: '[value="good"]',
        creditres:'Good',
        seven: '[value="Has never been in bankruptcy"]',
        sevenres:'Has never been in bankruptcy',
        street: '3564 N 2175 E',
        city2: 'Layton',
        fname: 'Joseph ',
        lname: 'Stone',
        email: 'stonepreston05@gmail.com',
        a: '[1]',
        b: '[2]',
        c: '[3]',
        d: '[4]',
        e: '[5]',
        f: '[6]',
        g: '[7]',
        h: '[8]',
        i: '[9]',
        j: '[10]',
        k: '[11]',
        l: '[12]',
        m: '[13]',
    },
    {
        drop1: '[value="Home Equity"]',
        drop1res: 'Home Equity',
        drop2: '[value="Town Home"]',
        drop2res: 'Town Home',
        city: 'lehi',
        prop: '[value="Secondary Home"]',
        propres: 'Secondary Home',
        idk: '[name="yesButton"]',
        idkres: 'True',
        idk2: '[name="noButton"]',
        idk2res:'False',
        pp: '100000',
        dp: '10000',
        credit: '[value="fair"]',
        creditres:'Fair',
        seven: '[value="Has had a foreclosure before"]',
        sevenres:'Has had a foreclosure before',
        street: '12341daawerew',
        city2: 'poop',
        fname: 'boober ',
        lname: 'doo',
        email: 'wow@froop@gmail.com',
        a: '[1]',
        b: '[2]',
        c: '[3]',
        d: '[4]',
        e: '[5]',
        f: '[6]',
        g: '[7]',
        h: '[8]',
        i: '[9]',
        j: '[10]',
        k: '[11]',
        l: '[12]',
        m: '[13]',
    },
    {
        drop1: '@ref',
        drop1res: 'Refinance',
        drop2: '@condo',
        drop2res: 'Condo',
        city: 'woosher',
        prop: '@RP',
        propres: 'Rental Property',
        idk: '[name="yesButton"]',
        idkres: 'True',
        idk2: '[name="noButton"]',
        idk2res:'False',
        pp: '1000000000',
        dp: '10000000',
        credit: '@excellent',
        creditres:'Excellent',
        seven: '@both',
        sevenres:'Has had both a foreclosure and a bankruptcy',
        street: '12341daawerew',
        city2: 'poop',
        fname: 'boober ',
        lname: 'doo',
        email: 'wow@froop@gmail.com',
        a: '[1]',
        b: '[2]',
        c: '[3]',
        d: '[4]',
        e: '[5]',
        f: '[6]',
        g: '[7]',
        h: '[8]',
        i: '[9]',
        j: '[10]',
        k: '[11]',
        l: '[12]',
        m: '[13]',
    }
]
